name = "week-13-offline"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL = ""
JWT_SECRET = ""
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# suppport for bucket is provided here
# wrangler r2 bucket list
# wrangler r2 bucket create hono-r2-upload
# automatically connects to our bucket
[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "hono-r2-upload"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
